[build]
  command = "npm ci --include=dev --prefix client && npm ci --include=dev --prefix server && npm run build"
  publish = "client/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

